Repository inf112-v20/error_brain_not_found, pull requests merged in 2020-02, with the labels that each got.

#9 Feature/board
  .gitignore
  mvn-app.iml
  pom.xml
  src/main/java/inf112/skeleton/app/Board.java
  src/main/java/inf112/skeleton/app/Main.java
  src/main/java/inf112/skeleton/app/Player.java
  src/main/java/inf112/skeleton/app/Position.java
  src/main/java/inf112/skeleton/app/assets/arrow.png
  src/main/java/inf112/skeleton/app/assets/kart.tmx
  src/main/java/inf112/skeleton/app/assets/textures.png
  src/test/java/inf112/skeleton/app/AppTest.java
  src/test/java/inf112/skeleton/app/board/BoardTest.java
  target/classes/META-INF/mvn-app.kotlin_module
Labels: enhancement

#11 Deliverables/oppgave1
  Deliverables/ObligatoriskOppgave1.md
Labels: documentation

#13 master v1.0
  .gitignore
  Deliverables/Obligatorisk Oppgave1/ClassDiagramMandatoryAssignment.uml
  Deliverables/Obligatorisk Oppgave1/ClassDiagramMandatoryAssignment1.png
  Deliverables/Obligatorisk Oppgave1/ObligatoriskOppgave1.md
  mvn-app.iml
  pom.xml
  src/main/java/inf112/skeleton/app/Board.java
  src/main/java/inf112/skeleton/app/HelloWorld.java
  src/main/java/inf112/skeleton/app/Main.java
  src/main/java/inf112/skeleton/app/Player.java
  src/main/java/inf112/skeleton/app/Position.java
  src/main/java/inf112/skeleton/app/assets/arrow.png
  src/main/java/inf112/skeleton/app/assets/kart.tmx
  src/main/java/inf112/skeleton/app/assets/textures.png
  src/test/java/inf112/skeleton/app/AppTest.java
  src/test/java/inf112/skeleton/app/PlayerTest.java
  src/test/java/inf112/skeleton/app/PositionTest.java
  target/classes/META-INF/mvn-app.kotlin_module
Labels: enhancement

#30 Feature/direction enums
  src/main/java/inf112/skeleton/app/Player.java
  src/main/java/inf112/skeleton/app/enums/Direction.java
  src/test/java/inf112/skeleton/app/DirectionTest.java
Labels: enhancement

#34 function movePlayer added
  src/main/java/inf112/skeleton/app/Board.java
  target/classes/META-INF/mvn-app.kotlin_module
Labels: enhancement

#41 Feature/program card
  src/main/java/inf112/skeleton/app/Board.java
  src/main/java/inf112/skeleton/app/RallyGame.java
  src/main/java/inf112/skeleton/app/cards/CardHand.java
  src/main/java/inf112/skeleton/app/cards/Deck.java
  src/main/java/inf112/skeleton/app/cards/ProgramCard.java
  src/main/java/inf112/skeleton/app/enums/Rotate.java
Labels: documentation, enhancement

#63 Refactor/make new deck
  src/main/java/inf112/skeleton/app/cards/Deck.java
Labels: documentation

#86 Mandatory Assignment v2.0
  .gitignore
  .travis.yml
  Deliverables/.DS_Store
  Deliverables/Obligatorisk Oppgave1/ClassDiagramMandatoryAssignment.uml
  Deliverables/Obligatorisk Oppgave1/ObligatoriskOppgave1.md
  Deliverables/Obligatorisk Oppgave2/ClassDiagramMandatoryAssignment2.png
  Deliverables/Obligatorisk Oppgave2/ClassDiagramMandatoryAssignment2.uml
  Deliverables/Obligatorisk Oppgave2/ObligatoriskOppgave2.md
  README.md
  assets/Dizzy_Dash.tmx
  assets/Island_Hop.tmx
  assets/Risky_Exchange.tmx
  assets/RoboRallyMenuScreen.png
  assets/player.png
  assets/player.tsx
  assets/testMap.tmx
  assets/tiles.tsx
  mvn-app.iml
  pom.xml
  src/main/java/inf112/skeleton/app/Board.java
  src/main/java/inf112/skeleton/app/BoardLayers.java
  src/main/java/inf112/skeleton/app/Main.java
  src/main/java/inf112/skeleton/app/Player.java
  src/main/java/inf112/skeleton/app/Position.java
  src/main/java/inf112/skeleton/app/RallyGame.java
  src/main/java/inf112/skeleton/app/assets/arrow.png
  src/main/java/inf112/skeleton/app/assets/kart.tmx
  src/main/java/inf112/skeleton/app/assets/textures.png
  src/main/java/inf112/skeleton/app/cards/CardHand.java
  src/main/java/inf112/skeleton/app/cards/Deck.java
  src/main/java/inf112/skeleton/app/cards/ProgramCard.java
  src/main/java/inf112/skeleton/app/enums/Direction.java
  src/main/java/inf112/skeleton/app/enums/Rotate.java
  src/main/java/inf112/skeleton/app/enums/TileID.java
  src/main/java/inf112/skeleton/app/objects/Flag.java
  src/main/java/inf112/skeleton/app/screens/GameScreen.java
  src/main/java/inf112/skeleton/app/screens/MenuScreen.java
  src/test/java/inf112/skeleton/app/BoardTest.java
  src/test/java/inf112/skeleton/app/DeckTest.java
  src/test/java/inf112/skeleton/app/DirectionTest.java
  src/test/java/inf112/skeleton/app/EmptyApplication.java
  src/test/java/inf112/skeleton/app/PlayerTest.java
  src/test/java/inf112/skeleton/app/PositionTest.java
  src/test/java/inf112/skeleton/app/ProgramCardTest.java
  target/classes/META-INF/mvn-app.kotlin_module
  target/test-classes/META-INF/mvn-app.kotlin_module
Labels: REALEASE, documentation, enhancement
